version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.5
        environment:
          SECRET_KEY_BASE: "test_secret"
    steps:
      - checkout
      - run: bundle install
      - run: bundle exec rake
